// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v5.29.3
// source: proto/lx_engine.proto

package engine

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Order types
type OrderSide int32

const (
	OrderSide_ORDER_SIDE_UNSPECIFIED OrderSide = 0
	OrderSide_ORDER_SIDE_BUY         OrderSide = 1
	OrderSide_ORDER_SIDE_SELL        OrderSide = 2
)

// Enum value maps for OrderSide.
var (
	OrderSide_name = map[int32]string{
		0: "ORDER_SIDE_UNSPECIFIED",
		1: "ORDER_SIDE_BUY",
		2: "ORDER_SIDE_SELL",
	}
	OrderSide_value = map[string]int32{
		"ORDER_SIDE_UNSPECIFIED": 0,
		"ORDER_SIDE_BUY":         1,
		"ORDER_SIDE_SELL":        2,
	}
)

func (x OrderSide) Enum() *OrderSide {
	p := new(OrderSide)
	*p = x
	return p
}

func (x OrderSide) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderSide) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_lx_engine_proto_enumTypes[0].Descriptor()
}

func (OrderSide) Type() protoreflect.EnumType {
	return &file_proto_lx_engine_proto_enumTypes[0]
}

func (x OrderSide) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderSide.Descriptor instead.
func (OrderSide) EnumDescriptor() ([]byte, []int) {
	return file_proto_lx_engine_proto_rawDescGZIP(), []int{0}
}

type OrderType int32

const (
	OrderType_ORDER_TYPE_UNSPECIFIED OrderType = 0
	OrderType_ORDER_TYPE_MARKET      OrderType = 1
	OrderType_ORDER_TYPE_LIMIT       OrderType = 2
	OrderType_ORDER_TYPE_STOP        OrderType = 3
	OrderType_ORDER_TYPE_STOP_LIMIT  OrderType = 4
)

// Enum value maps for OrderType.
var (
	OrderType_name = map[int32]string{
		0: "ORDER_TYPE_UNSPECIFIED",
		1: "ORDER_TYPE_MARKET",
		2: "ORDER_TYPE_LIMIT",
		3: "ORDER_TYPE_STOP",
		4: "ORDER_TYPE_STOP_LIMIT",
	}
	OrderType_value = map[string]int32{
		"ORDER_TYPE_UNSPECIFIED": 0,
		"ORDER_TYPE_MARKET":      1,
		"ORDER_TYPE_LIMIT":       2,
		"ORDER_TYPE_STOP":        3,
		"ORDER_TYPE_STOP_LIMIT":  4,
	}
)

func (x OrderType) Enum() *OrderType {
	p := new(OrderType)
	*p = x
	return p
}

func (x OrderType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_lx_engine_proto_enumTypes[1].Descriptor()
}

func (OrderType) Type() protoreflect.EnumType {
	return &file_proto_lx_engine_proto_enumTypes[1]
}

func (x OrderType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderType.Descriptor instead.
func (OrderType) EnumDescriptor() ([]byte, []int) {
	return file_proto_lx_engine_proto_rawDescGZIP(), []int{1}
}

type OrderStatus int32

const (
	OrderStatus_ORDER_STATUS_UNSPECIFIED      OrderStatus = 0
	OrderStatus_ORDER_STATUS_NEW              OrderStatus = 1
	OrderStatus_ORDER_STATUS_PARTIALLY_FILLED OrderStatus = 2
	OrderStatus_ORDER_STATUS_FILLED           OrderStatus = 3
	OrderStatus_ORDER_STATUS_CANCELED         OrderStatus = 4
	OrderStatus_ORDER_STATUS_REJECTED         OrderStatus = 5
)

// Enum value maps for OrderStatus.
var (
	OrderStatus_name = map[int32]string{
		0: "ORDER_STATUS_UNSPECIFIED",
		1: "ORDER_STATUS_NEW",
		2: "ORDER_STATUS_PARTIALLY_FILLED",
		3: "ORDER_STATUS_FILLED",
		4: "ORDER_STATUS_CANCELED",
		5: "ORDER_STATUS_REJECTED",
	}
	OrderStatus_value = map[string]int32{
		"ORDER_STATUS_UNSPECIFIED":      0,
		"ORDER_STATUS_NEW":              1,
		"ORDER_STATUS_PARTIALLY_FILLED": 2,
		"ORDER_STATUS_FILLED":           3,
		"ORDER_STATUS_CANCELED":         4,
		"ORDER_STATUS_REJECTED":         5,
	}
)

func (x OrderStatus) Enum() *OrderStatus {
	p := new(OrderStatus)
	*p = x
	return p
}

func (x OrderStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_lx_engine_proto_enumTypes[2].Descriptor()
}

func (OrderStatus) Type() protoreflect.EnumType {
	return &file_proto_lx_engine_proto_enumTypes[2]
}

func (x OrderStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderStatus.Descriptor instead.
func (OrderStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_lx_engine_proto_rawDescGZIP(), []int{2}
}

// Submit order
type SubmitOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Side          OrderSide              `protobuf:"varint,2,opt,name=side,proto3,enum=lx.engine.v1.OrderSide" json:"side,omitempty"`
	Type          OrderType              `protobuf:"varint,3,opt,name=type,proto3,enum=lx.engine.v1.OrderType" json:"type,omitempty"`
	Quantity      float64                `protobuf:"fixed64,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Price         float64                `protobuf:"fixed64,5,opt,name=price,proto3" json:"price,omitempty"`
	ClientOrderId string                 `protobuf:"bytes,6,opt,name=client_order_id,json=clientOrderId,proto3" json:"client_order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitOrderRequest) Reset() {
	*x = SubmitOrderRequest{}
	mi := &file_proto_lx_engine_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitOrderRequest) ProtoMessage() {}

func (x *SubmitOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lx_engine_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitOrderRequest.ProtoReflect.Descriptor instead.
func (*SubmitOrderRequest) Descriptor() ([]byte, []int) {
	return file_proto_lx_engine_proto_rawDescGZIP(), []int{0}
}

func (x *SubmitOrderRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *SubmitOrderRequest) GetSide() OrderSide {
	if x != nil {
		return x.Side
	}
	return OrderSide_ORDER_SIDE_UNSPECIFIED
}

func (x *SubmitOrderRequest) GetType() OrderType {
	if x != nil {
		return x.Type
	}
	return OrderType_ORDER_TYPE_UNSPECIFIED
}

func (x *SubmitOrderRequest) GetQuantity() float64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *SubmitOrderRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *SubmitOrderRequest) GetClientOrderId() string {
	if x != nil {
		return x.ClientOrderId
	}
	return ""
}

type SubmitOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Status        OrderStatus            `protobuf:"varint,2,opt,name=status,proto3,enum=lx.engine.v1.OrderStatus" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitOrderResponse) Reset() {
	*x = SubmitOrderResponse{}
	mi := &file_proto_lx_engine_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitOrderResponse) ProtoMessage() {}

func (x *SubmitOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lx_engine_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitOrderResponse.ProtoReflect.Descriptor instead.
func (*SubmitOrderResponse) Descriptor() ([]byte, []int) {
	return file_proto_lx_engine_proto_rawDescGZIP(), []int{1}
}

func (x *SubmitOrderResponse) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *SubmitOrderResponse) GetStatus() OrderStatus {
	if x != nil {
		return x.Status
	}
	return OrderStatus_ORDER_STATUS_UNSPECIFIED
}

func (x *SubmitOrderResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Cancel order
type CancelOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOrderRequest) Reset() {
	*x = CancelOrderRequest{}
	mi := &file_proto_lx_engine_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderRequest) ProtoMessage() {}

func (x *CancelOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lx_engine_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderRequest.ProtoReflect.Descriptor instead.
func (*CancelOrderRequest) Descriptor() ([]byte, []int) {
	return file_proto_lx_engine_proto_rawDescGZIP(), []int{2}
}

func (x *CancelOrderRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type CancelOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOrderResponse) Reset() {
	*x = CancelOrderResponse{}
	mi := &file_proto_lx_engine_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderResponse) ProtoMessage() {}

func (x *CancelOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lx_engine_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderResponse.ProtoReflect.Descriptor instead.
func (*CancelOrderResponse) Descriptor() ([]byte, []int) {
	return file_proto_lx_engine_proto_rawDescGZIP(), []int{3}
}

func (x *CancelOrderResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CancelOrderResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Order book
type GetOrderBookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Depth         int32                  `protobuf:"varint,2,opt,name=depth,proto3" json:"depth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderBookRequest) Reset() {
	*x = GetOrderBookRequest{}
	mi := &file_proto_lx_engine_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderBookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderBookRequest) ProtoMessage() {}

func (x *GetOrderBookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lx_engine_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderBookRequest.ProtoReflect.Descriptor instead.
func (*GetOrderBookRequest) Descriptor() ([]byte, []int) {
	return file_proto_lx_engine_proto_rawDescGZIP(), []int{4}
}

func (x *GetOrderBookRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *GetOrderBookRequest) GetDepth() int32 {
	if x != nil {
		return x.Depth
	}
	return 0
}

type PriceLevel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Price         float64                `protobuf:"fixed64,1,opt,name=price,proto3" json:"price,omitempty"`
	Quantity      float64                `protobuf:"fixed64,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	OrderCount    int32                  `protobuf:"varint,3,opt,name=order_count,json=orderCount,proto3" json:"order_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PriceLevel) Reset() {
	*x = PriceLevel{}
	mi := &file_proto_lx_engine_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PriceLevel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriceLevel) ProtoMessage() {}

func (x *PriceLevel) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lx_engine_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriceLevel.ProtoReflect.Descriptor instead.
func (*PriceLevel) Descriptor() ([]byte, []int) {
	return file_proto_lx_engine_proto_rawDescGZIP(), []int{5}
}

func (x *PriceLevel) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *PriceLevel) GetQuantity() float64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *PriceLevel) GetOrderCount() int32 {
	if x != nil {
		return x.OrderCount
	}
	return 0
}

type GetOrderBookResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Bids          []*PriceLevel          `protobuf:"bytes,2,rep,name=bids,proto3" json:"bids,omitempty"`
	Asks          []*PriceLevel          `protobuf:"bytes,3,rep,name=asks,proto3" json:"asks,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderBookResponse) Reset() {
	*x = GetOrderBookResponse{}
	mi := &file_proto_lx_engine_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderBookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderBookResponse) ProtoMessage() {}

func (x *GetOrderBookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lx_engine_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderBookResponse.ProtoReflect.Descriptor instead.
func (*GetOrderBookResponse) Descriptor() ([]byte, []int) {
	return file_proto_lx_engine_proto_rawDescGZIP(), []int{6}
}

func (x *GetOrderBookResponse) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *GetOrderBookResponse) GetBids() []*PriceLevel {
	if x != nil {
		return x.Bids
	}
	return nil
}

func (x *GetOrderBookResponse) GetAsks() []*PriceLevel {
	if x != nil {
		return x.Asks
	}
	return nil
}

func (x *GetOrderBookResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// Streaming
type StreamOrderBookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Depth         int32                  `protobuf:"varint,2,opt,name=depth,proto3" json:"depth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamOrderBookRequest) Reset() {
	*x = StreamOrderBookRequest{}
	mi := &file_proto_lx_engine_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamOrderBookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamOrderBookRequest) ProtoMessage() {}

func (x *StreamOrderBookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lx_engine_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamOrderBookRequest.ProtoReflect.Descriptor instead.
func (*StreamOrderBookRequest) Descriptor() ([]byte, []int) {
	return file_proto_lx_engine_proto_rawDescGZIP(), []int{7}
}

func (x *StreamOrderBookRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *StreamOrderBookRequest) GetDepth() int32 {
	if x != nil {
		return x.Depth
	}
	return 0
}

type OrderBookUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	BidUpdates    []*PriceLevel          `protobuf:"bytes,2,rep,name=bid_updates,json=bidUpdates,proto3" json:"bid_updates,omitempty"`
	AskUpdates    []*PriceLevel          `protobuf:"bytes,3,rep,name=ask_updates,json=askUpdates,proto3" json:"ask_updates,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	IsSnapshot    bool                   `protobuf:"varint,5,opt,name=is_snapshot,json=isSnapshot,proto3" json:"is_snapshot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderBookUpdate) Reset() {
	*x = OrderBookUpdate{}
	mi := &file_proto_lx_engine_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderBookUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderBookUpdate) ProtoMessage() {}

func (x *OrderBookUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lx_engine_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderBookUpdate.ProtoReflect.Descriptor instead.
func (*OrderBookUpdate) Descriptor() ([]byte, []int) {
	return file_proto_lx_engine_proto_rawDescGZIP(), []int{8}
}

func (x *OrderBookUpdate) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *OrderBookUpdate) GetBidUpdates() []*PriceLevel {
	if x != nil {
		return x.BidUpdates
	}
	return nil
}

func (x *OrderBookUpdate) GetAskUpdates() []*PriceLevel {
	if x != nil {
		return x.AskUpdates
	}
	return nil
}

func (x *OrderBookUpdate) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *OrderBookUpdate) GetIsSnapshot() bool {
	if x != nil {
		return x.IsSnapshot
	}
	return false
}

var File_proto_lx_engine_proto protoreflect.FileDescriptor

const file_proto_lx_engine_proto_rawDesc = "" +
	"\n" +
	"\x15proto/lx_engine.proto\x12\flx.engine.v1\"\xe0\x01\n" +
	"\x12SubmitOrderRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12+\n" +
	"\x04side\x18\x02 \x01(\x0e2\x17.lx.engine.v1.OrderSideR\x04side\x12+\n" +
	"\x04type\x18\x03 \x01(\x0e2\x17.lx.engine.v1.OrderTypeR\x04type\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x01R\bquantity\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x01R\x05price\x12&\n" +
	"\x0fclient_order_id\x18\x06 \x01(\tR\rclientOrderId\"}\n" +
	"\x13SubmitOrderResponse\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x121\n" +
	"\x06status\x18\x02 \x01(\x0e2\x19.lx.engine.v1.OrderStatusR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"/\n" +
	"\x12CancelOrderRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\"I\n" +
	"\x13CancelOrderResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"C\n" +
	"\x13GetOrderBookRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x14\n" +
	"\x05depth\x18\x02 \x01(\x05R\x05depth\"_\n" +
	"\n" +
	"PriceLevel\x12\x14\n" +
	"\x05price\x18\x01 \x01(\x01R\x05price\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x01R\bquantity\x12\x1f\n" +
	"\vorder_count\x18\x03 \x01(\x05R\n" +
	"orderCount\"\xa8\x01\n" +
	"\x14GetOrderBookResponse\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12,\n" +
	"\x04bids\x18\x02 \x03(\v2\x18.lx.engine.v1.PriceLevelR\x04bids\x12,\n" +
	"\x04asks\x18\x03 \x03(\v2\x18.lx.engine.v1.PriceLevelR\x04asks\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\"F\n" +
	"\x16StreamOrderBookRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x14\n" +
	"\x05depth\x18\x02 \x01(\x05R\x05depth\"\xde\x01\n" +
	"\x0fOrderBookUpdate\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x129\n" +
	"\vbid_updates\x18\x02 \x03(\v2\x18.lx.engine.v1.PriceLevelR\n" +
	"bidUpdates\x129\n" +
	"\vask_updates\x18\x03 \x03(\v2\x18.lx.engine.v1.PriceLevelR\n" +
	"askUpdates\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x12\x1f\n" +
	"\vis_snapshot\x18\x05 \x01(\bR\n" +
	"isSnapshot*P\n" +
	"\tOrderSide\x12\x1a\n" +
	"\x16ORDER_SIDE_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eORDER_SIDE_BUY\x10\x01\x12\x13\n" +
	"\x0fORDER_SIDE_SELL\x10\x02*\x84\x01\n" +
	"\tOrderType\x12\x1a\n" +
	"\x16ORDER_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11ORDER_TYPE_MARKET\x10\x01\x12\x14\n" +
	"\x10ORDER_TYPE_LIMIT\x10\x02\x12\x13\n" +
	"\x0fORDER_TYPE_STOP\x10\x03\x12\x19\n" +
	"\x15ORDER_TYPE_STOP_LIMIT\x10\x04*\xb3\x01\n" +
	"\vOrderStatus\x12\x1c\n" +
	"\x18ORDER_STATUS_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10ORDER_STATUS_NEW\x10\x01\x12!\n" +
	"\x1dORDER_STATUS_PARTIALLY_FILLED\x10\x02\x12\x17\n" +
	"\x13ORDER_STATUS_FILLED\x10\x03\x12\x19\n" +
	"\x15ORDER_STATUS_CANCELED\x10\x04\x12\x19\n" +
	"\x15ORDER_STATUS_REJECTED\x10\x052\xe8\x02\n" +
	"\rEngineService\x12R\n" +
	"\vSubmitOrder\x12 .lx.engine.v1.SubmitOrderRequest\x1a!.lx.engine.v1.SubmitOrderResponse\x12R\n" +
	"\vCancelOrder\x12 .lx.engine.v1.CancelOrderRequest\x1a!.lx.engine.v1.CancelOrderResponse\x12U\n" +
	"\fGetOrderBook\x12!.lx.engine.v1.GetOrderBookRequest\x1a\".lx.engine.v1.GetOrderBookResponse\x12X\n" +
	"\x0fStreamOrderBook\x12$.lx.engine.v1.StreamOrderBookRequest\x1a\x1d.lx.engine.v1.OrderBookUpdate0\x01B8Z6github.com/luxexchange/engine/backend/pkg/proto/engineb\x06proto3"

var (
	file_proto_lx_engine_proto_rawDescOnce sync.Once
	file_proto_lx_engine_proto_rawDescData []byte
)

func file_proto_lx_engine_proto_rawDescGZIP() []byte {
	file_proto_lx_engine_proto_rawDescOnce.Do(func() {
		file_proto_lx_engine_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_lx_engine_proto_rawDesc), len(file_proto_lx_engine_proto_rawDesc)))
	})
	return file_proto_lx_engine_proto_rawDescData
}

var file_proto_lx_engine_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_proto_lx_engine_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_lx_engine_proto_goTypes = []any{
	(OrderSide)(0),                 // 0: lx.engine.v1.OrderSide
	(OrderType)(0),                 // 1: lx.engine.v1.OrderType
	(OrderStatus)(0),               // 2: lx.engine.v1.OrderStatus
	(*SubmitOrderRequest)(nil),     // 3: lx.engine.v1.SubmitOrderRequest
	(*SubmitOrderResponse)(nil),    // 4: lx.engine.v1.SubmitOrderResponse
	(*CancelOrderRequest)(nil),     // 5: lx.engine.v1.CancelOrderRequest
	(*CancelOrderResponse)(nil),    // 6: lx.engine.v1.CancelOrderResponse
	(*GetOrderBookRequest)(nil),    // 7: lx.engine.v1.GetOrderBookRequest
	(*PriceLevel)(nil),             // 8: lx.engine.v1.PriceLevel
	(*GetOrderBookResponse)(nil),   // 9: lx.engine.v1.GetOrderBookResponse
	(*StreamOrderBookRequest)(nil), // 10: lx.engine.v1.StreamOrderBookRequest
	(*OrderBookUpdate)(nil),        // 11: lx.engine.v1.OrderBookUpdate
}
var file_proto_lx_engine_proto_depIdxs = []int32{
	0,  // 0: lx.engine.v1.SubmitOrderRequest.side:type_name -> lx.engine.v1.OrderSide
	1,  // 1: lx.engine.v1.SubmitOrderRequest.type:type_name -> lx.engine.v1.OrderType
	2,  // 2: lx.engine.v1.SubmitOrderResponse.status:type_name -> lx.engine.v1.OrderStatus
	8,  // 3: lx.engine.v1.GetOrderBookResponse.bids:type_name -> lx.engine.v1.PriceLevel
	8,  // 4: lx.engine.v1.GetOrderBookResponse.asks:type_name -> lx.engine.v1.PriceLevel
	8,  // 5: lx.engine.v1.OrderBookUpdate.bid_updates:type_name -> lx.engine.v1.PriceLevel
	8,  // 6: lx.engine.v1.OrderBookUpdate.ask_updates:type_name -> lx.engine.v1.PriceLevel
	3,  // 7: lx.engine.v1.EngineService.SubmitOrder:input_type -> lx.engine.v1.SubmitOrderRequest
	5,  // 8: lx.engine.v1.EngineService.CancelOrder:input_type -> lx.engine.v1.CancelOrderRequest
	7,  // 9: lx.engine.v1.EngineService.GetOrderBook:input_type -> lx.engine.v1.GetOrderBookRequest
	10, // 10: lx.engine.v1.EngineService.StreamOrderBook:input_type -> lx.engine.v1.StreamOrderBookRequest
	4,  // 11: lx.engine.v1.EngineService.SubmitOrder:output_type -> lx.engine.v1.SubmitOrderResponse
	6,  // 12: lx.engine.v1.EngineService.CancelOrder:output_type -> lx.engine.v1.CancelOrderResponse
	9,  // 13: lx.engine.v1.EngineService.GetOrderBook:output_type -> lx.engine.v1.GetOrderBookResponse
	11, // 14: lx.engine.v1.EngineService.StreamOrderBook:output_type -> lx.engine.v1.OrderBookUpdate
	11, // [11:15] is the sub-list for method output_type
	7,  // [7:11] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_proto_lx_engine_proto_init() }
func file_proto_lx_engine_proto_init() {
	if File_proto_lx_engine_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_lx_engine_proto_rawDesc), len(file_proto_lx_engine_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_lx_engine_proto_goTypes,
		DependencyIndexes: file_proto_lx_engine_proto_depIdxs,
		EnumInfos:         file_proto_lx_engine_proto_enumTypes,
		MessageInfos:      file_proto_lx_engine_proto_msgTypes,
	}.Build()
	File_proto_lx_engine_proto = out.File
	file_proto_lx_engine_proto_goTypes = nil
	file_proto_lx_engine_proto_depIdxs = nil
}
