services:
  # PostgreSQL Database (required for DEX)
  postgres:
    image: postgres:16-alpine
    container_name: lux-dex-db
    environment:
      - POSTGRES_DB=luxdex
      - POSTGRES_USER=dexuser
      - POSTGRES_PASSWORD=dexpass123
      - POSTGRES_MAX_CONNECTIONS=200
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dexuser -d luxdex"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # Redis Cache (required for DEX)
  redis:
    image: redis:7-alpine
    container_name: lux-dex-redis
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres-data:
    driver: local
  redis-data:
    driver: local