apiVersion: apps/v1
kind: Deployment
metadata:
  name: lxdex
  namespace: lxdex-staging
  labels:
    app: lxdex
    environment: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lxdex
  template:
    metadata:
      labels:
        app: lxdex
        environment: staging
    spec:
      containers:
      - name: lxdex
        image: registry.lux.network/lxdex:staging
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 8081
          name: websocket
        - containerPort: 50051
          name: grpc
        env:
        - name: ENVIRONMENT
          value: "staging"
        - name: LOG_LEVEL
          value: "debug"
        - name: CONSENSUS_K
          value: "1"
        - name: ENGINE_TYPE
          value: "go"
        resources:
          requests:
            memory: "2Gi"
            cpu: "1"
          limits:
            memory: "4Gi"
            cpu: "2"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5