apiVersion: v1
kind: Service
metadata:
  name: lxdex
  namespace: lxdex-staging
spec:
  type: LoadBalancer
  selector:
    app: lxdex
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  - port: 443
    targetPort: 8081
    protocol: TCP
    name: websocket
  - port: 50051
    targetPort: 50051
    protocol: TCP
    name: grpc