apiVersion: v1
kind: Secret
metadata:
  name: lxdex-secrets
  namespace: lxdex-production
type: Opaque
stringData:
  # Database credentials
  postgres_host: "postgres.lxdex-production.svc.cluster.local"
  postgres_port: "5432"
  postgres_db: "lxdex"
  postgres_user: "lxdex"
  postgres_password: "CHANGE_ME_IN_PRODUCTION"
  
  # Redis credentials
  redis_host: "redis.lxdex-production.svc.cluster.local"
  redis_port: "6379"
  redis_password: "CHANGE_ME_IN_PRODUCTION"
  
  # NATS credentials
  nats_url: "nats://nats.lxdex-production.svc.cluster.local:4222"
  nats_cluster_id: "lxdex-cluster"
  nats_client_id: "lxdex-node"
  
  # JWT signing key
  jwt_secret: "CHANGE_ME_IN_PRODUCTION_USE_STRONG_SECRET"
  
  # API keys for external services
  prometheus_token: "CHANGE_ME_IN_PRODUCTION"
  grafana_api_key: "CHANGE_ME_IN_PRODUCTION"
---
apiVersion: v1
kind: Secret
metadata:
  name: lxdex-tls
  namespace: lxdex-production
type: kubernetes.io/tls
data:
  # Base64 encoded TLS certificate and key
  # Generate real certificates for production
  tls.crt: |
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCi4uLkNoYW5nZSBNZSBJbiBQcm9kdWN0aW9uLi4uCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  tls.key: |
    LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCi4uLkNoYW5nZSBNZSBJbiBQcm9kdWN0aW9uLi4uCi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K