name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: "1.21"
    
    - name: Install dependencies
      working-directory: ./backend
      run: |
        go mod download
        go mod tidy
    
    - name: Run tests
      working-directory: ./backend
      run: |
        go test -v -short ./pkg/lx/...
    
  benchmark:
    name: Benchmark
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: "1.21"
    
    - name: Run benchmarks
      working-directory: ./backend
      run: |
        echo "Running 581M benchmark..."
        go test -bench=Benchmark581M -benchtime=1s ./pkg/lx/... || true
        
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: "1.21"
    
    - name: Build binaries
      working-directory: ./backend
      run: |
        echo "Building LX consensus..."
        CGO_ENABLED=0 go build -o bin/lx-consensus ./cmd/xchain-dex/
        
        echo "Building benchmark tool..."
        CGO_ENABLED=0 go build -o bin/bench-all ./cmd/bench-all/
        
        echo "All binaries built successfully!"
