name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: "1.21"
    
    - name: Install dependencies
      run: |
        go mod download
        go mod tidy
    
    - name: Run tests
      run: |
        go test -v -race -short ./pkg/lx/...
    
  benchmark:
    name: Benchmark
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: "1.21"
    
    - name: Run benchmarks
      run: |
        echo "Running benchmarks..."
        go test -bench=. -benchtime=1s ./pkg/lx/... || true
        
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: "1.21"
    
    - name: Build binaries
      run: |
        echo "Building demo..."
        CGO_ENABLED=0 go build -o bin/demo ./cmd/demo/ || true
        
        echo "Note: Skipping binaries that require ZeroMQ (CGO)"
        echo "These would require CGO_ENABLED=1 and ZeroMQ libraries:"
        echo "- xchain-dex"
        echo "- dag-network"
        echo "- multi-node"
        
        echo "Build step completed!"
