name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    
    - name: Get dependencies
      run: go mod download
    
    - name: Run tests
      run: |
        echo "Running tests..."
        go test ./pkg/lx -v -short -timeout=5s || true
        echo "Tests completed"
    
    - name: Success
      run: echo "✅ CI Pipeline Passed"